import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "http-equiv": "origin-trial",
    content:
      "AvV8N6LoZ7oxNLUIwl8vMDDQLqZwj8dn/cIytZgKysdWhZ0WQtv0Vqb0poo3SzTgdeVlkKZX852gjVp/HoKegA4AAACGeyJvcmlnaW4iOiJodHRwczovL2huZzEyLXN0ZzMtYWktdGV4dC1wcm9jZXNzb3IudmVyY2VsLmFwcDo0NDMiLCJmZWF0dXJlIjoiQUlTdW1tYXJpemF0aW9uQVBJIiwiZXhwaXJ5IjoxNzUzMTQyNDAwLCJpc1N1YmRvbWFpbiI6dHJ1ZX0=",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
